language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - py.test --cov=gloss --cov-report=html
after_success: coveralls
notifications:
  slack: ohcuk:6spaME3CB7f2PGrMAcklYWqp
sudo: false
